### ISSUE TITLE
Feature Request: allow smaller x-axis dimension of image capture.

### ISSUE THREAD

**Issue by jmhjr** [Nain57/Smart-AutoClicker#105]
I would like to be able to shrink the x-axis of the image capture to the size of the y-axis.

**Comment by Efreak** [comment]
This would be very useful. In fact, I'd like to even just set color of a single pixel, as I'm only looking at a certain spot on a progress bar to see if it's red or green. The progress bar is rather short and has other UI around it, as well as a text overlay, and I only want my actions to proceed if the progress bar is red; after a while, the text overlay changes so much the action gets stopped, so I need multiple conditions for the progress bar. Since the overlay isn't a simple percentage and changes quickly, I've had to set up multiple conditions based on the status of UI elements nearby; this is impossible in some places where the UI changes too fast.

**Comment by jmhjr** [comment]
This can be closed. Discovered you can zoom to create the size needed.
