### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by Vatsune** [Nain57/Smart-AutoClicker#116]
The ability to specify an area in which to find images rather than the entire screen would be great.
Also, when tapping location is set to condition, being able to set the position to tap relative to the found location would help; a simpler "top/bottom right/left corner" and "center" selection would also be great.

**Comment by OkazakiLeir** [comment]
The "tap relative to the found location" feature would be a very nice addition indeed, since sometimes the tap misses the action if it's set to a certain location and the actionable area changes a little bit above/below that area. Another way to do it would be tapping right in the center of the image that was set, wherever it may be.
