### ISSUE TITLE
How to change between apps

### ISSUE THREAD

**Issue by yant0** [Nain57/Smart-AutoClicker#12]
i couldnt go out after opening an app, when i assign smart-autoclicker to press any button in bottom navigation, it places it self at 0,0 (left top)
solutions?

**Comment by Nain57** [comment]
Not sure I understand the issue.

When you say it moves to 0,0, you are talking about the floating menu ?  Is the screen orientation changing when starting the "other application" ?

**Comment by Nain57** [comment]
So you are trying to automatize a click on your navigation bar but the click position is always set to 0.0 instead of the required position ?

This seems like an issue, I will take a look at this once I have some time to work on this application. Can you provide me a bit more of information ? Your device, your Android version, screen orientation and position of the navigation bar (bottom or side ?).

**Comment by yant0** [comment]
sure
Asus zenfone max pro m1
Android 9 stock
Orientation 0
Navigation bar bottom
also this
![Imagepipe_0](https://user-images.githubusercontent.com/80298071/123970100-99e2d180-d997-11eb-840f-63e3780933e1.jpg)

**Comment by Nain57** [comment]
This might be fixed in RC4, available here: https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.0-RC4

As said in the attached commit message, it is not possible to draw with an overlay over the navigation bar. But the corrections made in the coordinates system should allow the click correctly on it.
