### ISSUE TITLE
“Import/Export/ Save macro settings” and “Hide controls”

### ISSUE THREAD

**Issue by luffaBoy** [Nain57/Smart-AutoClicker#122]
Hello Devs,

First of all thank you for making such an awesome and simplistic to use app.

The app itself is very good, however can I ask that the function to save, import and export the “macro settings” to another emulator to be made available.
It would be really nice to be able to save multiple macro settings as well.

Also it would be really nice to be able to “Hide controls” to have a clean screen; maybe add function to make controls reappear by “pressing home” or dragging down status menu ?

Lastly if you can add “toggle buttons” on each action that would be useful for testing ! 🙂

Once again great work and thanks for sharing with us ! <3

**Comment by DaMaddCyantist** [comment]
Hey @Nain57 

Rehashing to talk about exporting.
I know you mentioned [exporting is turned off due to screen resolutions](https://github.com/Nain57/Smart-AutoClicker/issues/37#issuecomment-919055125), however shouldn't this caveat by the responsibility of the user?

Obviously a person on a Pixel XL cannot "easily" share their exact macro w/ a Pixel 3 user, however, the framework is there, and that should be more than enough to get started (for the Pixel 3 user).

Just wondering if you've thought about it more. Thanks.

**Comment by Nain57** [comment]
![Screenshot_20220519-210419.jpg](https://user-images.githubusercontent.com/8599025/169382426-28ea70ef-1404-416e-86b2-2be85f4614fb.jpg)

🤫🤫🤫

**Comment by Nain57** [comment]
Import/Export have been implemented since 1.5.0
