### ISSUE TITLE
adding the condition splits the screen in half on landscape mode

### ISSUE THREAD

**Issue by luminatethelumia** [Nain57/Smart-AutoClicker#128]
after updating to 1.4.0 whenever i try to add a condition the screen will split in half, and some of the old conditions in landscape mode also broke, im using android 12
![Screenshot_20220515-120252_Discord](https://user-images.githubusercontent.com/83003355/168458455-345e0791-b277-4d8c-8e79-b7dc8cde9de7.jpg)

**Comment by Flindgh** [comment]
Hi,
I have the same issue with landscape scenarios, since the upgrade to v1.4.0.
In addition, when defining à click action, only the left part of the screen is available. Same for moving the bar: can only be moved on the left part of the screen.
And finally, all my previous scenarios (in landscape mode) are now broken: no automated click at all (and the debug mode shows 0%).
Samsung Galaxy A70, Android 11.

**Comment by Nain57** [comment]
Hi and thanks for your feedback !
This is related to the bluestacks support patch, it seems like all Android devices like to report their screen size and orientation differently. I will fix it as soon as possible and release it with the next version.
Sorry for the trouble !
