### ISSUE TITLE
After renaming a scenario, the scenario name in the list does not take effect.

### ISSUE THREAD

**Issue by Hackergeek** [Nain57/Smart-AutoClicker#183]

**Comment by Hackergeek** [comment]
Modifying the onRenameClicked method in the ScenarioListFragment.kt file can solve this problem. The modified code is as follows:
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/9377994/192971703-fe5122d6-766d-4b46-a230-2bec30aae337.png">

**Comment by Nain57** [comment]
Hi and thanks for your feedback.

I have completely forgot about that feature, it's not even in my release test process. This might be broken since 6 month at least -_-'.
The name was actually correctly updated, it was the UI that wasn't refreshed (killing and restarting the app effectively shows the last name).

The bug is fixed: https://github.com/Nain57/Smart-AutoClicker/commit/2d0f87771b8401b61779919873d00bf670a26a87
It will part of the next release.

**Comment by Nain57** [comment]
Release 2.0.0 containing a fix for this is now available on Github and should be available soon on F-Droid.
