### ISSUE TITLE
[Feature request] Pause on physical button press

### ISSUE THREAD

**Issue by Dimava** [Nain57/Smart-AutoClicker#201]
If clicker clicks too fast, it's sometimes impossible to stop it with click on screen

Thus I would like to have an option to pause clicking on  volume change or screen block

**Comment by Metazolid** [comment]
Easiest workaround is to open the camera my double clicking the screen lock button, that removes whatever your scenario is detecting and you can pause or stop like usual. Another option would be to rapidly tapping the play/pause button, it can take a couple attempts but it works.

Whenever I have a scenario where it happens frequently, I just put a 50-100ms wait period after the press action, that's enough to make pausing easy.

**Comment by jiongjiongJOJO** [comment]
I don't think this can be marked as a bug, it should be a new feature. The feature of the tool is to quickly identify the designated area and complete the operation such as clicking, so multiple clicks in a short period of time should not be considered as a bug. also most similar tools use the volume down key to pause the current task, because the volume key is not absolutely conflicting with the current task.
@Nain57

**Comment by Dimava** [comment]
Thanks for implementing this lol
Wonder how many phones did I change since then
Time to reinstall I guess

**Comment by Nain57** [comment]
Just to let you know, it's the volume down button (there is a dialog explaining it, but I have several users that didn't saw it)
