### ISSUE TITLE
Change  processingScope from Dispatchers.IO to  Dispatchers.Default

### ISSUE THREAD

**Issue by laiqun** [Nain57/Smart-AutoClicker#205]
processingScope = CoroutineScope(Dispatchers.IO)
Dispathers.Default performs better because it equals the CPU core's num.

**Comment by Nain57** [comment]
Smart AutoClicker processing is mono threaded, having more thread will not impact performance

**Comment by laiqun** [comment]
Yes, it mono threaded, but diff Dispatchers have diff meaning.

- Dispatchers.Default for computation-intensive task.
- Dispatchers.IO for IO-intensive task.

I think image process is more compuation than IO.

**Comment by Nain57** [comment]
I have tested the efficiency of both a lot, and I can assure you that both are exactly similar in performance for Smart AutoClicker due to it's mono-threaded architecture (as there is no context switching)

There is one case where IO have proven itself better is when using a scenario with a lot of condition images, the image cache can't be big enough to store all of them and will start to throw away old images to load the needed ones from the disk (in order to prevent an OOM exception). 

In this case, using IO instead of simply Default (or Default and switching context to IO for image loading) was way better performance wise.
