### ISSUE TITLE
[BUG] Missing Accessibility service permission

### ISSUE THREAD

**Issue by KiritoStorm** [Nain57/Smart-AutoClicker#22]
My problem is that I have often restart my phone when I want to use the app. I have set the accessibility permission and it is also set when try to change it. 
It doesn't even work when I toggle the setting on and off on my Xiaomi Redmi K20. (MIUI 12.0.5 based on Android 10, unrooted) 

On the screenshot you see how it looks like when the setting isn't right detected. 
![IMG_20210712_113407](https://user-images.githubusercontent.com/46503102/125265625-4e201880-e305-11eb-88e3-22dc45c84dff.jpg)

**Comment by Nain57** [comment]
This behaviour occurs when the AccessibilityService have crashed on Android 10 and above. On those versions, simply enabling the service back again doesn't seems to trigger the starting of the service by the system. I have noticed it a lot during the developpement because the same thing is happening when I reinstall the application over a running one.

I have found a workaround for this, I enable and disable the service quickly, wait 5s, and enable it again. This seems to force Android to restart the service.

That being said, in your case, if this bug is happening, this means the Smart AutoClicker accessibility service is crashing, which is not normal. Have you already made it successfully work ? Have you noticed unexpected shutdown of the service ? (menu/notification disappearing)

**Comment by KiritoStorm** [comment]
Thank you for the answer and the workaround, I will try it out and see if there is any unexpected behavior.

Von: ***@***.***>
Gesendet: Mittwoch, 14. Juli 2021 12:02
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [Nain57/Smart-AutoClicker] [BUG] Missing Accessibility service permission (#22)


This behaviour occurs when the AccessibilityService have crashed on Android 10 and above. On those versions, simply enabling the service back again doesn't seems to trigger the starting of the service by the system. I have noticed it a lot during the developpement because the same thing is happening when I reinstall the application over a running one.

I have found a workaround for this, I enable and disable the service quickly, wait 5s, and enable it again. This seems to force Android to restart the service.

That being said, in your case, if this bug is happening, this means the Smart AutoClicker accessibility service is crashing, which is not normal. Have you already made it successfully work ? Have you noticed unexpected shutdown of the service ? (menu/notification disappearing)

**Comment by irwanwr** [comment]
I also experienced this problem. 
Though for my side, I believe this happens whenever pre-installed cleaner of Xiaomi Redmi was used. It seems that the cleaner removed the "accessibility permission's agent" in the background.

**Comment by Nain57** [comment]
Thank you for this clarification !
After validating with a friend, it seems like this Xiaomi cleaner is removing the permission.
