### ISSUE TITLE
Single click initiates multiple clicks

### ISSUE THREAD

**Issue by josephg5** [Nain57/Smart-AutoClicker#263]
I have to add a wait after every click or it keeps clicking. I have an accessibility shortcut for triple-click, and often I find this app triple-click (or maybe more) when I have only a click as action.

**Comment by shmaungms** [comment]
I have a feeling you are going to have to add a wait after your clicks. I have done this to stop multiple clicks on almost every event.  It is the nature of the program. The problem is that for some events people may want it to keep detecting and clicking quickly so fixing the multiple click problem would stop it working for them.

The app could have an option to run the event once and not run it again until after another event runs. Or better still have that as default and an option to run the event more than once repeatedly. Actually this would be nice feature to have in the future as it would help stop a scenario from going rogue. (which has happened to me)

**Comment by Nain57** [comment]
@josephg5 This is not a bug, you need to put a wait action after your click. If you do not, the next frame will be evaluated immediately and if the condition is still on it, your action will be executed again.

@shmaungms This is already possible by using the event state feature.

**Comment by josephg5** [comment]
A single-click is not double-click triple-click etc which are different events. Executing a single-click should not result in executing a double-click or triple-click or quadruple-click etc. But I accept what you say. Guess it is far simpler this way as you have it now, for those with nano seconds requirements.

**Comment by Nain57** [comment]
A double click is simply 2 quick simple clic. 
How do you expect the OS to do the difference ?

The app is open source, if you think you can do better, do it yourself.
