### ISSUE TITLE
Does "wait" apply to all events?

### ISSUE THREAD

**Issue by LSworn** [Nain57/Smart-AutoClicker#291]
I'm trying to have an event "wait" x amount of seconds before it starts detecting the condition because I have another event on the same page to do something else but it doesn't seem to work the way I think it would. Is there a way to do this?

What I'm trying to do is basically having 1 event with multiple conditions trying to detect if there is at least one HP bar above a certain percent to click and I have a 2nd event to wait out x amount of seconds for the first event to check for anything to click and if not then  refresh the page

**Comment by wordpad25** [comment]
All logic is done via enabling and disabling events. 

If X condition matches you need to disable Y condition and enable your X event etc

**Comment by Nain57** [comment]
It is difficult to answer such questions without some screenshots to understand what you are trying to achieve.
If you need to execute an action only when condition A is displayed but condition B is not displayed, you can change the visibility attribute of the condition B to Absent.

**Comment by Anuragroyan** [comment]
you can achieve this functionality by utilizing timers, event listeners, and actions triggered by those events. Here's how you could implement it -
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import androidx.appcompat.app.AppCompatActivity

class MainActivity : AppCompatActivity() {
    private val hpThreshold = 50 // Adjust this threshold as needed
    private val refreshDelay = 5000 // Adjust this refresh delay in milliseconds as needed

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        // Simulate the change in HP bars or whatever triggers the need to click
        simulateHPBarsChanged()
    }

    private fun simulateHPBarsChanged() {
        // Check conditions for clicking based on HP bars
        val hpBars = listOf(60, 30, 80, 40) // Example HP bars percentages

        val clickNeeded = hpBars.any { it > hpThreshold }

        if (!clickNeeded) {
            // If no click is needed, start the timer to refresh the page
            Handler(Looper.getMainLooper()).postDelayed({
                // Perform action to refresh the page
                refreshPage()
            }, refreshDelay.toLong())
        } else {
            // Perform the click action here
            performClickAction()
        }
    }

    private fun performClickAction() {
        // Perform the action of clicking here
        // For example, you can simulate a click on a button or any UI element
    }

    private fun refreshPage() {
        // Perform action to refresh the page
        // For example, you can reload the current activity or navigate to a new one
        // For demonstration, let's just print a message here
        println("Refreshing page...")
    }
}

here is the example-
simulateHPBarsChanged() is called to check the conditions for clicking based on HP bars. If any HP bar percentage is above the threshold, it triggers the click action. Otherwise, it schedules a refresh after a certain delay.

performClickAction() would contain the logic to perform the click action. This could involve clicking on a button or any other UI element programmatically.

refreshPage() would contain the logic to refresh the page. You can replace the placeholder logic with actual code to refresh the page.

**Comment by Anuragroyan** [comment]
i hope this help you little.
