### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by Mohmotte** [Nain57/Smart-AutoClicker#298]
If a picture is find, it start the application but I must restart the application instead of start the application...

**Comment by Mohmotte** [comment]
I think I must change "android.intent.action.MAIN" into a command to restart the application but I don't understand...

**Comment by Nain57** [comment]
Hi and thanks for your feedback.
This question has been asked countless times, Smart Autoclicker is not a task manager and Intent API doesn't provide a way to kill an app. Instead, you can automate the gestures to be executed on your device to kill it manually.

Closed due to duplicate + Invalid title and labels.
