### ISSUE TITLE
Auto Clicks stops working after long hours of use

### ISSUE THREAD

**Issue by Mr-Kumar-Abhishek** [Nain57/Smart-AutoClicker#325]
**Auto Clicks stop working after long hour use**
Auto Clicks of scenarios stop working after long hours of use. I use the pro version of this app. And while using for 12 hours or more continuously the clicks stop working even though the scenario is on play.

**To Reproduce**
1. Make a complex scenario with multiple conditions for clicks
2. Start the scenario
3. Let it play for 12 hours straight minimum
4. See the auto clicks stop working after few hours 

**Expected behavior**
I should be able to use it as long as I as like. And auto clicks should work no matter how long it is running.

**Detection scenario**
[SmartAutoClicker-Backup.zip](https://github.com/Nain57/Smart-AutoClicker/files/12844916/SmartAutoClicker-Backup.zip)

**Smartphone :**
 - Device: Redmi 9 A
 - Android OS version: Android 10
 - Smart AutoClicker version 2.1.4

**Comment by Nain57** [comment]
Hi and thank you for your feedback.

This can happen due to two things:
* A crash of Smart Autoclicker. You are using 2.1.4, which an old version, you might want to update it (current version is 2.3.1)
* You system have arbitrarily killed Smart AutoClicker. This is a famous issue, especially on some brands. You might want to take a look at this website, it contains some suggestions that can help: https://dontkillmyapp.com

**Comment by stoykovstoyk** [comment]
According to this Issue:

I have detected a small memory leak which is present in most present in versions 2.3.1 - 2.3.6 (I haven't tested any older version then 2.3.1) 
The leak is very small and if you run the autoclicker on mid range device you might not be able to see it. But if you run it on less powerful devices you will see app crash after several hours of use or less. 
I have manage to detect the memory leak using logcat and currently I am running Android Studio Profiler trying to detect where the leak happens, but I am not an expert and I am not absolutely sure will I be able to figure out where it is.
I can provide a log file if necessary to show how I detected it, but since it is very long I decided to provide it only if requested, because I do not want to make this thread hard to read with long log files.

One very  quick and dirty solutions is to request for larger Heap size with  android:largeHeap="true" which worked on some of my devices, but this is not recommended solution at all.

**Comment by ricjonsu-impact360** [comment]
I am using the most recent version, and I also tried to compile it myself. I can attest that the app does not work after several hours on some lower-end devices, especially those with small RAM. The app is running, but it won't detect any conditions. I had to force kill the app and run it again in order for it to work.

**Comment by Nain57** [comment]
Closed: Old bug format and stability have improved since. If you still have issues, please open a new ticket.
