### ISSUE TITLE
2.3.2 Crashes as soon as starting a scenario 

### ISSUE THREAD

**Issue by Kellett** [Nain57/Smart-AutoClicker#334]
**Describe the bug**
App crashes when trying to start a scenario 

**To Reproduce**
1. Fresh install/ Clear data
2. Create scenario
3. Give it any name
4. Play the scenario
5. Enable all missing permissions
6. Click Start Now on the recording prompt
7. Sidebar/menu never appears and the app crashes

**Expected behavior**
The sidebar menu overlay should show to allow configuration of the scenario

**Detection scenario**
NA

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 8 Pro
 - Android OS version: Android 14 (October build)
 - Smart AutoClicker version: 2.3.2 (Play store)

**Comment by Kellett** [comment]
If anyone else seems this remove the play store version and install 2.3.4 from GitHub and it will start working. You'll lose your scenarios so backup first

**Comment by Nain57** [comment]
Already fixed in 2.3.3, crash only occurs on Android 14.
This has been already been released (should be available in the next days on FDroid, or on GitHub, in the release section)

The PlayStore version causes me some problems, as they refused the 2.3.3 due to the accessibility service not requested explicitly enough (even if the dialog haven't changed in a year...)
I have changed it in 2.3.4, and I'm now waiting for they're approval.

**Comment by Nain57** [comment]
Update: 2.3.4 has also been rejected, but they have been less criptic about the problem.

I will create a 2.3.5 this weekend. Sorry for the inconvenience
