### ISSUE TITLE
Tutorial (Press when Red): Score counts backwards when auto clicked

### ISSUE THREAD

**Issue by MKrabs** [Nain57/Smart-AutoClicker#337]
**Describe the bug**
When manually trying the 3rd tutorial, the score counts up. When trying the automated way, it counts down. 

**To Reproduce**

https://github.com/Nain57/Smart-AutoClicker/assets/71791731/2da565da-17f1-42ee-85f4-b7dfde15bd54

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S23
 - Android OS version: 13
 - Smart AutoClicker version 2.3.2

**Comment by tian2105** [comment]
In fact, 3rd scenario has a more important issues : it contains no action however tutorial lead says the opposite, then it refuses to save and eventually it does what previous scenario does.
If i try to put an action, the tutorial stops, hence i cannot go further into learning and i'm pretty sad :(

PS : thanks for this tool, already doing great saving me some time watching a countdown... :+1:

**Comment by Nain57** [comment]
They was an issue in the default detection quality applied to tutorial scenarios than might lead to your decreasing score issue (the autoclicker is clicking on the wrong charater i think)

Next version will fix that, let me know if you still have the problem

**Comment by coolguy001tv** [comment]
I am facing this problem in 2.4.2. In the 3rd tutorial, because of counting down, i can't get 50 scores.  I manage to get more than 50 by setting the blue one's detection type from FullScreen to section, and choose left half of screen.(Sorry I am using Chinese, so the translation may be not accurate). See the pic below.
After this, it tells me I can move to next. But back to tutorial, there're still 3 chapters. So ther're only 3  chapters?
![a1401325547217859c47d8c5ac32ec9](https://github.com/Nain57/Smart-AutoClicker/assets/936825/a825f469-d8a0-4f05-9502-2abdc4d6c1a3)
![0839112c33af6a768d1b6a10277e14c](https://github.com/Nain57/Smart-AutoClicker/assets/936825/142bdc88-617c-4b97-8a7b-08ad45596d2d)
