### ISSUE TITLE
Suggestion: Line to define middle screen, detect pixel color, export file

### ISSUE THREAD

**Issue by kizl01** [Nain57/Smart-AutoClicker#37]
1. I play some games that have to rotate the camera a lot to do Quests, fishing,... Because of "?" and "!" marks located in the middle of the character's head, every time I rotate the camera, I have to make another screenshot to make auto click works. And if I change spots, I have to do that again. So, It'll be cool to create a square ( to detect pixel color ) or a line that defines the middle screen.
2. And those "?" and "!" marks have a lot of colors ( blue for side quests, yellow for main quest,... ) so maybe detect pixel color is good for this too.
3. I use your app on many devices so is there any way to export Scenarios I have created in a file and use it for other devices, instead of making new one.

Thanks you for making this app.

**Comment by brigs111** [comment]
An export setting would be wonderful.

**Comment by Nain57** [comment]
Hi!

* 1: This will be very tricky to implement, and very conditional as this rotation behaviour is very specific to your game.
* 2: For more fine detection options, this will requires to use OpenCV or another computer vision library to replace my simple matching algorithm. This is a huge enhancement I'd like to do, as it will allow a lot of new features, but this is not the projet priority right now.
* 3: I have blocked the export because my current algorithm depends on the screen metrics (size and resolution). Exporting from a device A to a device B will not work, unless their screens are exactly identical. Resolving 2 might allow it.

**Comment by Nain57** [comment]
Most of it is now implemented, the rest is irrelevant to the current state of the app
