### ISSUE TITLE
Lock on always true condition

### ISSUE THREAD

**Issue by tian2105** [Nain57/Smart-AutoClicker#370]
**Describe the bug**
As soon as one event is always true, it will start twice in a row then loop, and never go to next step

**To Reproduce**
Create a first event always true
Choose a swipe up
Pause for 10s

Create a second event always true
Choose a swipe down
Pause for 1s

**Obtained scenario**
swipe up -> "<1s" -> swipe up -> 10s ->...

**Expected behavior**
I don't know if we want this to run parallel or serial so 2 behaviours would be rather rational :
1) swipe ups happening every 10 s and, in the same time, swipe down every second..
2) swipe up -> 10s ->swipe down -> 1s ->...

**Smartphone**
 - Device: Google Pixel 4a 5G
 - Android OS version: LineageOS - Android 13
 - Smart AutoClicker version : 2.4.1 (from f-droid.org)

**Comment by Nain57** [comment]
This is the intended behaviour. If an Event have its screen conditions fulfilled, it will execute and the execution will stop for this screen frame. So as long as the first Event in the list is visible on the screen, the second will not execute. That's why you can reorder the Events in the list.

You can also control which Events are active with the ToggleEvent Action.
