### ISSUE TITLE
Autoclicker doesn't loop

### ISSUE THREAD

**Issue by jvachez** [Nain57/Smart-AutoClicker#377]
**Describe the bug**
Autoclicker doesn't loop it doesn't click again on event 1 image

**To Reproduce**
Event 1 
- Click
- Event 1 Status desactivated

Event 2
- Click
- Pause
- Click
- Event 1 Status activated

**Expected behavior**
Reexecute Event 1 after Event 2 executed

**Smartphone (please complete the following information):**
 - Pixel 7 Pro
 - Android OS version: 14
 - Smart AutoClicker version 2.4.1

**Comment by kimxdhaha** [comment]
Same situation, its always goto Switch to Alliance Page instead of Unoccupied Check, tried add an adsent scenario to block it skipping but not working

![IMG_1804](https://github.com/Nain57/Smart-AutoClicker/assets/14929565/a8f08354-cf02-4de1-9e83-104d927329f7)
![IMG_1806](https://github.com/Nain57/Smart-AutoClicker/assets/14929565/4072f266-1e25-423f-b721-5883b9aae116)
![IMG_1805](https://github.com/Nain57/Smart-AutoClicker/assets/14929565/48ec5b65-59fd-45d0-bbd9-76bb69beaaf3)

**Comment by Nain57** [comment]
Trigger events features haev been completly remade in version 3. 
If you encounter another issue, please open a new ticket.
