### ISSUE TITLE
No way to restore purchase

### ISSUE THREAD

**Issue by zachpipher123** [Nain57/Smart-AutoClicker#396]
I purchased premium on the app but now i wanted to put the application on my PC on an android emulator but there is no way to see how to restore my purchase on another device. Which is a problem because if my phone was to be compromised even with a backup I wouldn't be able to restore the app anyways because that is only usable to a premium user.

**Comment by Mobilpadde** [comment]
I'm gonna jump into this as well. Different-ish issue though. Every after the latest update, with the renaming, it keeps asking me to buy pro, which I already did. I reinstalled it and this fixed the issue, now, it's been a few days since I opened it last and the issue is back.

**Comment by Nain57** [comment]
Hi and thank you for your feedback.

Google required to update the billing library or the application would have been removed from the play store, but ever since, I have a lot of users emailing for the same issue. Klick'r is not keeping a local cache on the purchase state, and rely on the Google Play Services to get it. Unfortunately, with the last version of their library, it seems like this source of information is not really reliable.

I have found a way to fix (it worked with most of the users that have emailed me), you need to clear the cache of the Google Play Services:

- Execute the three steps described [here](https://support.google.com/googleplay/answer/9037938?hl=en) in order to correctly clean your cache.
- Reboot your phone and ensure you have an internet connection.
- Start the Google PlayStore app to see if it is correctly functional and then check Klick'r.

Let me know if this solves your problem.

**Comment by Mobilpadde** [comment]
@Nain57 thanks 🙏 That did the trick.

I always forget the auto update from the Play Store can be slow, but I updated Google Play Services and cleared its cache. That did the trick, so I suspect I only had to do one of those, but well. Works now 🙌

**Comment by Nain57** [comment]
Just to clarify why there is no "restore purchase" button: Klick'r is refreshing the purchase state from the Google Play Services automatically everytime the list of scenario is displayed (in dev language, in the [onResume](https://github.com/Nain57/Smart-AutoClicker/blob/master/smartautoclicker/src/main/java/com/buzbuz/smartautoclicker/activity/ScenarioActivity.kt#L85)of the Activity). Adding one will just be redundant and would not solve the issue.

I'm keeping this issue as pinned in the bug section in order for newcomers to find the [solution](https://github.com/Nain57/Smart-AutoClicker/issues/396#issuecomment-2313229697).

**Comment by touyets** [comment]
Hi Nain. I have tried the solution steps outlined above twice to no avail (it did work on my phone personnaly, just not the tablet for my girlfriend who also purchased her premium subscription). Are there extra troubleshooting steps I can follow to fix this issue for her?

**Comment by Nain57** [comment]
Hi,

Besides retrying the procedure while ensuring a stable internet connection, I have no other tips (one user emailed me and had the same issue, retrying the steps have fixed it for him). 

For the follow up, the bug has been accepted by Google in their issue tracker, which means they recognize that the issue is on their side, but knowing them, it will not be fixed soon...

If you can't solve your issue, I can refund your girlfriend, just please me an email containing the Google Account that made the purchase (my address is attached to my github profile, or in the playstore page of Klick'r, under the section "Support"). From there, you will be free to buy it again (or not, do as you please :) ), as the bug is not impacting new purchases.

**Comment by Nain57** [comment]
I would really be interrested by a bug report of a device that have the issue, as this will provide additional data for my bug report to Google.

In case someone have this issue and is willing to help before performing the steps to fix it, can you:
* Reboot your phone
* Start Klick'r and go up to the screen requesting you to pay
* Exit the screen and generate the bug report
* Send me the generated zip file (by email if you are concerned about privacy, or here if you don't care)

Here is a simple visual documentation about how to create a bug report: https://support.avast.com/en-ww/article/create-android-bug-report/#pc

This will be really helpful to understand what is exactly happening, and this can help me find a temporary fix in the code if there is any.

**Comment by touyets** [comment]
Hey Nain,

We managed to fix it with a 3rd attempt. Potentially the play service
didn't fully remove the data before.

Really appreciate you offering the refund.

Btw, killer app!!!! I (we acrually) really love it.

Thanks,

Simon and Valérie

**Comment by Nain57** [comment]
Hi all,

I have added a few workarounds in 3.0.3 released two weeks ago (i forgot to mention it the release note). Email complaints seems to have stopped since.

Does anybody here have reproduced the issue ?

**Comment by Mobilpadde** [comment]
Seems to have been working for me 🎉 Great job!
