### ISSUE TITLE
Transparent images/icons not detected as condition

### ISSUE THREAD

**Issue by 0lm** [Nain57/Smart-AutoClicker#402]
**Describe the bug**
Image Condition which have transparence are not detected, because the colors in the transparent area change according to background changes (or moving icon).
**To Reproduce**
1. Any App or Game which have a transparent images/icons (example: a circle image, but inside its filled with transparency)
2. Create Smart Macro and select the transparent icon on the screen and set it as a click condition.

**Expected behavior**
Detection.

**Detection scenario**
Not necessary, since this is not limited to a certain scenario of mine, but to all scenarios which have transparent image conditions.

**Screenshots**
Not needed, see "Detection Scenario"

**Smartphone (please complete the following information):**
This issue is independent from phone model.

**Comment by Cyber5imon** [comment]
Because the selected area is a rectangle, the icon background will affect the detection as you mentioned.

Creating the ability to scan for custom shaped objects is not possible at this time.

Your best option is to zoom in the screen capture so you are only checking the icon with as little background showing as possible, and set the tolerance to 20% allowing more changes to the background. You may still need to create 3 conditions for light, medium, and dark backgrounds.

**Comment by Nain57** [comment]
Closed: not a bug but more a feature request. If you think this is relevant, please create a new Feature Request ticket.
