### ISSUE TITLE
Klick'r stops working when phone overheats

### ISSUE THREAD

**Issue by RStanbouly** [Nain57/Smart-AutoClicker#486]
### Version of Smart AutoClicker

3.0.2

### Device brand and model

Galaxy S21 Ultra

### Version of your Android OS

14

### Type

Smart scenario

### Describe what happened?

Running Smart Scenario
Working fine
Phone begins to overheat due to mixture of Klick'r and the app that klick'r is tapping on 
Pause button becomes unable to be tapped - klick'r no longer analyzing screen or attempting to tap on anything
Close klick'r, reopen, unable to press play button after starting a klick'r scenario
Required to force close before klick'r begins to work again
Accessibility settings are still enabled

### Describe what should have happened?

Klick'r should have continued to work as expected.

**Comment by hafbtm** [comment]
Did you find a solution to this problem? I'm having the same error, sometimes it lasts up to an hour before it happens again, sometimes it even happens in 4 minutes or less, I have battery optimization Disabled for klikr, it will still always stop

**Comment by hafbtm** [comment]
Maybe allowing the app to be used as a device administrator would work to keep it running always? I could make it optional in the klikr menu

**Comment by Nain57** [comment]
Hi and thank you for your feedback.

This is a known issue with Samsumg devices and background processes. Samsung is not following AOSP guidelines about background process management and can kill apps even if they should be running. You can follow the guidelines available [here](https://dontkillmyapp.com) in order to mitigate the problem.

As there is nothing I can do about this issue as a independant developer, I will close this issue.
