### ISSUE TITLE
The order of clicks is wrong.

### ISSUE THREAD

**Issue by PpLpP22** [Nain57/Smart-AutoClicker#487]
### Version of Smart AutoClicker

3.0.0-3.0.2

### Device brand and model

Vivo iqoo 3 5G & Poco F4

### Version of your Android OS

13 & 14

### Type

Other

### Describe what happened?

explain with a video.

https://github.com/user-attachments/assets/91d09ddd-a637-411d-92aa-e11fe134129f

https://files.catbox.moe/vri0to.mp4

### Describe what should have happened?

Should be version 2.4.2

**Comment by Nain57** [comment]
Hi and thank you for your feedback.

You have been confused by the changes of the bottom left and right buttons.
In 2.4.2, they were changing the displayed action, just like a swipe left or right. (they were redundant with those gesture, that's why I changed them)
In 3.x.x, I have changed them to reorder them in the list of actions (icons have changed as well). 

With those changes in mind, I don't see any unexepected behaviour on your video, both versions are OK
