### ISSUE TITLE
counter wont count

### ISSUE THREAD

**Issue by LostLinguine** [Nain57/Smart-AutoClicker#497]
### Version of Smart AutoClicker

3.0.2

### Device brand and model

oneplus 8t

### Version of your Android OS

11

### Type

Smart scenario

### Describe what happened?

Seems to have an issue counting the right trigger or just doesnt count at all, ive seen that re naming triggers or events can fix it but its not reliable and idk why it cant activate the trigger when everything matches and there should be no reason that it can count and activate the trigger.. even when i get the triggers to count properly and work it cant loop the triggers and only works 1 time and enabling triggers doesnt seem to do anything

### Describe what should have happened?

I expected when it starts counting it can find the right trigger and the trigger will activate and disable the event i need it to and when the event is enabled again i can  enable the trigger again and have it loop but it does neither easily.
[raid_unity.zip](https://github.com/user-attachments/files/17003311/raid_unity.zip)
I tried making a bot with it and for some reason event "stare" cant count and activate the "z" trigger and use the counter called "move" (i have it disabled in the file i have above but that was from testing along with the weird names for the triggers.. it didnt work even when enabled so i just tried something different to no success) not matter what i did i couldnt get it to count and for some reason some events didnt want to be enabled after being disabled so thats kinda hard to work around

**Comment by Nain57** [comment]
Hi and thank you for your feedback.

I haven't been able to reproduce the issue on my side. Can you provide a scenario with just the sequence of actions that causes the counting issue ? 

On a side note, I have seen that some of your events are using the ToggleEvent actions. A bug have been [acknowledged ](https://github.com/Nain57/Smart-AutoClicker/issues/501) with those actions, the order of the events enabled/disabled can be messed up and lead to invalids behaviours. This might be the root cause of your problem.

**Comment by Nain57** [comment]
Without any news, I consider this ticket as fixed.
If you are still encountering the issue on version 3.0.6 and above, feel free to reopen it.
