### ISSUE TITLE
Lost Ad Free after update

### ISSUE THREAD

**Issue by ItsLemonDrizzle** [Nain57/Smart-AutoClicker#564]
### Version of Smart AutoClicker

3.1.0

### Apk

PlayStore

### Device brand and model

Pixel Fold

### Version of your Android OS

15

### Type

Other

### Describe what happened?

I purchased Ad Free pro a while ago but now it is asking me to watch ads and pay for pro again.

### Describe what should have happened?

Continue with my lifetime pro status.

**Comment by ItsLemonDrizzle** [comment]
This suddenly started happening today and my scenario import no longer seem to work properly anymore either.

**Comment by Nain57** [comment]
Hi and thank you for your feedback.



This issue can come from an invalid cache of the Google Play Services on your phone, as Klick'r doesn't keep a cache of the purchase but ask to google everytime it needs it.

Execute the three steps described [here](https://support.google.com/googleplay/answer/9037938?hl=en) in order to correctly clean your cache.
Reboot your phone and ensure you have an internet connection.
Start the Google PlayStore app to see if it is correctly functional and then check Klick'r.

Let me know if this solves your problem.

**Comment by ItsLemonDrizzle** [comment]
Hey, thanks for the quick reply. It worked but the import still seems
broken but I can fix that and do a new back up.

Really appreciate it.

Dan

**Comment by Nain57** [comment]
There is already a issue opened: https://github.com/Nain57/Smart-AutoClicker/issues/561

I will fix it in next version, most likely this weekend

**Comment by ItsLemonDrizzle** [comment]
thanks clearing cache for play store worked.
