### ISSUE TITLE
Backup/Restore app data

### ISSUE THREAD

**Issue by Thomas-678** [Nain57/Smart-AutoClicker#94]
Currently, this app doesn't provide any way to backup data. Even adb backup doesn't work because _android:allowBackup_ is false and the target sdk version is android 12 (disallow adb backup of app data).

I can see two scenarios where backup/restore of data is helpful or necessary. The scripted procedures may work on another phone with the same resolution and DPI. And all your settings will be lost if you wipe your phone or migrate to another phone.

I think a quick solution would be to store the app's config under /sdcard/Android/data/com.buzbuz.smartautoclicker, so that we don't need root to backup app data.

**Comment by Nain57** [comment]
I don't use allowBackup because, according to the google documentation "The amount of data is limited to 25MB per user of your app", and 25MB is too small once you have to many conditions (I rather have no backup than have a broken one).
For the public folder solution, I'm worried about users deleting images conditions and then trying to execute a scenario using those conditions.

A solution will be to implements a custom backup system.

**Comment by Efreak** [comment]
Custom backup could be as simple as zipping the data folder and changing the extension.
